import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import math

__weights_dict = dict()

def load_weights(weight_file):
    if weight_file == None:
        return

    try:
        weights_dict = np.load(weight_file, allow_pickle=True).item()
    except:
        weights_dict = np.load(weight_file, encoding='bytes', allow_pickle=True).item()

    return weights_dict

class KitModel(nn.Module):

    
    def __init__(self, weight_file):
        super(KitModel, self).__init__()
        global __weights_dict
        __weights_dict = load_weights(weight_file)

        self.vargface_head_conv1 = self.__conv(2, name='vargface_head_conv1', in_channels=3, out_channels=40, kernel_size=(3, 3), stride=(1, 1), groups=1, bias=False)
        self.vargface_head_conv1_bn = self.__batch_normalization(2, 'vargface_head_conv1_bn', num_features=40, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_head_head_pooling_sep1_data_conv2d_depthwise = self.__conv(2, name='vargface_head_head_pooling_sep1_data_conv2d_depthwise', in_channels=40, out_channels=40, kernel_size=(3, 3), stride=(2, 2), groups=5, bias=False)
        self.vargface_head_head_pooling_shortcut_conv2d_depthwise = self.__conv(2, name='vargface_head_head_pooling_shortcut_conv2d_depthwise', in_channels=40, out_channels=40, kernel_size=(3, 3), stride=(2, 2), groups=5, bias=False)
        self.vargface_head_head_pooling_sep1_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_head_head_pooling_sep1_data_conv2d_depthwise_bn', num_features=40, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_head_head_pooling_shortcut_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_head_head_pooling_shortcut_conv2d_depthwise_bn', num_features=40, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_head_head_pooling_sep1_data_conv2d_pointwise = self.__conv(2, name='vargface_head_head_pooling_sep1_data_conv2d_pointwise', in_channels=40, out_channels=40, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_head_head_pooling_shortcut_conv2d_pointwise = self.__conv(2, name='vargface_head_head_pooling_shortcut_conv2d_pointwise', in_channels=40, out_channels=40, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_head_head_pooling_sep1_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_head_head_pooling_sep1_data_conv2d_pointwise_bn', num_features=40, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_head_head_pooling_shortcut_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_head_head_pooling_shortcut_conv2d_pointwise_bn', num_features=40, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_head_head_pooling_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_head_head_pooling_sep2_data_conv2d_depthwise', in_channels=40, out_channels=40, kernel_size=(3, 3), stride=(1, 1), groups=5, bias=False)
        self.vargface_head_head_pooling_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_head_head_pooling_sep2_data_conv2d_depthwise_bn', num_features=40, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_head_head_pooling_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_head_head_pooling_sep2_data_conv2d_pointwise', in_channels=40, out_channels=40, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_head_head_pooling_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_head_head_pooling_sep2_data_conv2d_pointwise_bn', num_features=40, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise = self.__conv(2, name='vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise', in_channels=40, out_channels=80, kernel_size=(3, 3), stride=(2, 2), groups=5, bias=False)
        self.vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise = self.__conv(2, name='vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise', in_channels=40, out_channels=80, kernel_size=(3, 3), stride=(2, 2), groups=5, bias=False)
        self.vargface_stage_2_unit_1_shortcut_conv2d_depthwise = self.__conv(2, name='vargface_stage_2_unit_1_shortcut_conv2d_depthwise', in_channels=40, out_channels=80, kernel_size=(3, 3), stride=(2, 2), groups=5, bias=False)
        self.vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_bn', num_features=80, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_bn', num_features=80, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_1_shortcut_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_1_shortcut_conv2d_depthwise_bn', num_features=80, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise = self.__conv(2, name='vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise', in_channels=80, out_channels=80, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise = self.__conv(2, name='vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise', in_channels=80, out_channels=80, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_2_unit_1_shortcut_conv2d_pointwise = self.__conv(2, name='vargface_stage_2_unit_1_shortcut_conv2d_pointwise', in_channels=80, out_channels=80, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise_bn', num_features=80, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise_bn', num_features=80, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_1_shortcut_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_1_shortcut_conv2d_pointwise_bn', num_features=80, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_1_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_2_unit_1_sep2_data_conv2d_depthwise', in_channels=80, out_channels=160, kernel_size=(3, 3), stride=(1, 1), groups=10, bias=False)
        self.vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_1_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_2_unit_1_sep2_data_conv2d_pointwise', in_channels=160, out_channels=80, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_2_unit_1_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_1_sep2_data_conv2d_pointwise_bn', num_features=80, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_2_sep1_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_2_unit_2_sep1_data_conv2d_depthwise', in_channels=80, out_channels=160, kernel_size=(3, 3), stride=(1, 1), groups=10, bias=False)
        self.vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_2_sep1_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_2_unit_2_sep1_data_conv2d_pointwise', in_channels=160, out_channels=80, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_bn', num_features=80, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_2_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_2_unit_2_sep2_data_conv2d_depthwise', in_channels=80, out_channels=160, kernel_size=(3, 3), stride=(1, 1), groups=10, bias=False)
        self.vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_2_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_2_unit_2_sep2_data_conv2d_pointwise', in_channels=160, out_channels=80, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_2_unit_2_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_2_sep2_data_conv2d_pointwise_bn', num_features=80, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_3_sep1_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_2_unit_3_sep1_data_conv2d_depthwise', in_channels=80, out_channels=160, kernel_size=(3, 3), stride=(1, 1), groups=10, bias=False)
        self.vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_3_sep1_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_2_unit_3_sep1_data_conv2d_pointwise', in_channels=160, out_channels=80, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_bn', num_features=80, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_3_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_2_unit_3_sep2_data_conv2d_depthwise', in_channels=80, out_channels=160, kernel_size=(3, 3), stride=(1, 1), groups=10, bias=False)
        self.vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_2_unit_3_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_2_unit_3_sep2_data_conv2d_pointwise', in_channels=160, out_channels=80, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_2_unit_3_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_2_unit_3_sep2_data_conv2d_pointwise_bn', num_features=80, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise', in_channels=80, out_channels=160, kernel_size=(3, 3), stride=(2, 2), groups=10, bias=False)
        self.vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise', in_channels=80, out_channels=160, kernel_size=(3, 3), stride=(2, 2), groups=10, bias=False)
        self.vargface_stage_3_unit_1_shortcut_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_1_shortcut_conv2d_depthwise', in_channels=80, out_channels=160, kernel_size=(3, 3), stride=(2, 2), groups=10, bias=False)
        self.vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_1_shortcut_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_1_shortcut_conv2d_depthwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise', in_channels=160, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise', in_channels=160, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_1_shortcut_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_1_shortcut_conv2d_pointwise', in_channels=160, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_1_shortcut_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_1_shortcut_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_1_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_1_sep2_data_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(1, 1), groups=20, bias=False)
        self.vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_1_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_1_sep2_data_conv2d_pointwise', in_channels=320, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_1_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_1_sep2_data_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_2_sep1_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_2_sep1_data_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(1, 1), groups=20, bias=False)
        self.vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_2_sep1_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_2_sep1_data_conv2d_pointwise', in_channels=320, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_2_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_2_sep2_data_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(1, 1), groups=20, bias=False)
        self.vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_2_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_2_sep2_data_conv2d_pointwise', in_channels=320, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_2_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_2_sep2_data_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_3_sep1_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_3_sep1_data_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(1, 1), groups=20, bias=False)
        self.vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_3_sep1_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_3_sep1_data_conv2d_pointwise', in_channels=320, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_3_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_3_sep2_data_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(1, 1), groups=20, bias=False)
        self.vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_3_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_3_sep2_data_conv2d_pointwise', in_channels=320, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_3_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_3_sep2_data_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_4_sep1_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_4_sep1_data_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(1, 1), groups=20, bias=False)
        self.vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_4_sep1_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_4_sep1_data_conv2d_pointwise', in_channels=320, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_4_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_4_sep2_data_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(1, 1), groups=20, bias=False)
        self.vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_4_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_4_sep2_data_conv2d_pointwise', in_channels=320, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_4_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_4_sep2_data_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_5_sep1_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_5_sep1_data_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(1, 1), groups=20, bias=False)
        self.vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_5_sep1_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_5_sep1_data_conv2d_pointwise', in_channels=320, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_5_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_5_sep2_data_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(1, 1), groups=20, bias=False)
        self.vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_5_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_5_sep2_data_conv2d_pointwise', in_channels=320, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_5_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_5_sep2_data_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_6_sep1_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_6_sep1_data_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(1, 1), groups=20, bias=False)
        self.vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_6_sep1_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_6_sep1_data_conv2d_pointwise', in_channels=320, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_6_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_6_sep2_data_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(1, 1), groups=20, bias=False)
        self.vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_6_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_6_sep2_data_conv2d_pointwise', in_channels=320, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_6_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_6_sep2_data_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_7_sep1_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_7_sep1_data_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(1, 1), groups=20, bias=False)
        self.vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_7_sep1_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_7_sep1_data_conv2d_pointwise', in_channels=320, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_7_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_3_unit_7_sep2_data_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(1, 1), groups=20, bias=False)
        self.vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_3_unit_7_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_3_unit_7_sep2_data_conv2d_pointwise', in_channels=320, out_channels=160, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_3_unit_7_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_3_unit_7_sep2_data_conv2d_pointwise_bn', num_features=160, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise = self.__conv(2, name='vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(2, 2), groups=20, bias=False)
        self.vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise = self.__conv(2, name='vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(2, 2), groups=20, bias=False)
        self.vargface_stage_4_unit_1_shortcut_conv2d_depthwise = self.__conv(2, name='vargface_stage_4_unit_1_shortcut_conv2d_depthwise', in_channels=160, out_channels=320, kernel_size=(3, 3), stride=(2, 2), groups=20, bias=False)
        self.vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_1_shortcut_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_1_shortcut_conv2d_depthwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise = self.__conv(2, name='vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise', in_channels=320, out_channels=320, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise = self.__conv(2, name='vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise', in_channels=320, out_channels=320, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_4_unit_1_shortcut_conv2d_pointwise = self.__conv(2, name='vargface_stage_4_unit_1_shortcut_conv2d_pointwise', in_channels=320, out_channels=320, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_1_shortcut_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_1_shortcut_conv2d_pointwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_1_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_4_unit_1_sep2_data_conv2d_depthwise', in_channels=320, out_channels=640, kernel_size=(3, 3), stride=(1, 1), groups=40, bias=False)
        self.vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_bn', num_features=640, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_1_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_4_unit_1_sep2_data_conv2d_pointwise', in_channels=640, out_channels=320, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_4_unit_1_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_1_sep2_data_conv2d_pointwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_2_sep1_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_4_unit_2_sep1_data_conv2d_depthwise', in_channels=320, out_channels=640, kernel_size=(3, 3), stride=(1, 1), groups=40, bias=False)
        self.vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_bn', num_features=640, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_2_sep1_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_4_unit_2_sep1_data_conv2d_pointwise', in_channels=640, out_channels=320, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_2_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_4_unit_2_sep2_data_conv2d_depthwise', in_channels=320, out_channels=640, kernel_size=(3, 3), stride=(1, 1), groups=40, bias=False)
        self.vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_bn', num_features=640, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_2_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_4_unit_2_sep2_data_conv2d_pointwise', in_channels=640, out_channels=320, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_4_unit_2_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_2_sep2_data_conv2d_pointwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_3_sep1_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_4_unit_3_sep1_data_conv2d_depthwise', in_channels=320, out_channels=640, kernel_size=(3, 3), stride=(1, 1), groups=40, bias=False)
        self.vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_bn', num_features=640, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_3_sep1_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_4_unit_3_sep1_data_conv2d_pointwise', in_channels=640, out_channels=320, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_3_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_4_unit_3_sep2_data_conv2d_depthwise', in_channels=320, out_channels=640, kernel_size=(3, 3), stride=(1, 1), groups=40, bias=False)
        self.vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_bn', num_features=640, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_3_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_4_unit_3_sep2_data_conv2d_pointwise', in_channels=640, out_channels=320, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_4_unit_3_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_3_sep2_data_conv2d_pointwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_4_sep1_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_4_unit_4_sep1_data_conv2d_depthwise', in_channels=320, out_channels=640, kernel_size=(3, 3), stride=(1, 1), groups=40, bias=False)
        self.vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_bn', num_features=640, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_4_sep1_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_4_unit_4_sep1_data_conv2d_pointwise', in_channels=640, out_channels=320, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_4_sep2_data_conv2d_depthwise = self.__conv(2, name='vargface_stage_4_unit_4_sep2_data_conv2d_depthwise', in_channels=320, out_channels=640, kernel_size=(3, 3), stride=(1, 1), groups=40, bias=False)
        self.vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_bn', num_features=640, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.vargface_stage_4_unit_4_sep2_data_conv2d_pointwise = self.__conv(2, name='vargface_stage_4_unit_4_sep2_data_conv2d_pointwise', in_channels=640, out_channels=320, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.vargface_stage_4_unit_4_sep2_data_conv2d_pointwise_bn = self.__batch_normalization(2, 'vargface_stage_4_unit_4_sep2_data_conv2d_pointwise_bn', num_features=320, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.embed_convx = self.__conv(2, name='embed_convx', in_channels=320, out_channels=1024, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.embed_convx_bn = self.__batch_normalization(2, 'embed_convx_bn', num_features=1024, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.embed_convx_depthwise = self.__conv(2, name='embed_convx_depthwise', in_channels=1024, out_channels=1024, kernel_size=(7, 7), stride=(1, 1), groups=128, bias=False)
        self.embed_convx_depthwise_bn = self.__batch_normalization(2, 'embed_convx_depthwise_bn', num_features=1024, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.embed_convx_pointwise = self.__conv(2, name='embed_convx_pointwise', in_channels=1024, out_channels=512, kernel_size=(1, 1), stride=(1, 1), groups=1, bias=False)
        self.embed_convx_pointwise_bn = self.__batch_normalization(2, 'embed_convx_pointwise_bn', num_features=512, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
        self.pre_fc1 = self.__dense(name = 'pre_fc1', in_features = 512, out_features = 512, bias = True)
        self.fc1 = self.__batch_normalization(0, 'fc1', num_features=512, eps=1.9999999494757503e-05, momentum=0.8999999761581421)

    def forward(self, x):
        self.minusscalar0_second = torch.autograd.Variable(torch.from_numpy(__weights_dict['minusscalar0_second']['value']), requires_grad=False)
        self.mulscalar0_second = torch.autograd.Variable(torch.from_numpy(__weights_dict['mulscalar0_second']['value']), requires_grad=False)
        minusscalar0    = x - self.minusscalar0_second
        mulscalar0      = minusscalar0 * self.mulscalar0_second
        vargface_head_conv1_pad = F.pad(mulscalar0, (1, 1, 1, 1))
        vargface_head_conv1 = self.vargface_head_conv1(vargface_head_conv1_pad)
        vargface_head_conv1_bn = self.vargface_head_conv1_bn(vargface_head_conv1)
        vargface_head_conv1_act = F.prelu(vargface_head_conv1_bn, torch.from_numpy(__weights_dict['vargface_head_conv1_act']['weights']))
        vargface_head_head_pooling_sep1_data_conv2d_depthwise_pad = F.pad(vargface_head_conv1_act, (1, 1, 1, 1))
        vargface_head_head_pooling_sep1_data_conv2d_depthwise = self.vargface_head_head_pooling_sep1_data_conv2d_depthwise(vargface_head_head_pooling_sep1_data_conv2d_depthwise_pad)
        vargface_head_head_pooling_shortcut_conv2d_depthwise_pad = F.pad(vargface_head_conv1_act, (1, 1, 1, 1))
        vargface_head_head_pooling_shortcut_conv2d_depthwise = self.vargface_head_head_pooling_shortcut_conv2d_depthwise(vargface_head_head_pooling_shortcut_conv2d_depthwise_pad)
        vargface_head_head_pooling_sep1_data_conv2d_depthwise_bn = self.vargface_head_head_pooling_sep1_data_conv2d_depthwise_bn(vargface_head_head_pooling_sep1_data_conv2d_depthwise)
        vargface_head_head_pooling_shortcut_conv2d_depthwise_bn = self.vargface_head_head_pooling_shortcut_conv2d_depthwise_bn(vargface_head_head_pooling_shortcut_conv2d_depthwise)
        vargface_head_head_pooling_sep1_data_conv2d_depthwise_act = F.prelu(vargface_head_head_pooling_sep1_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_head_head_pooling_sep1_data_conv2d_depthwise_act']['weights']))
        vargface_head_head_pooling_shortcut_conv2d_depthwise_act = F.prelu(vargface_head_head_pooling_shortcut_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_head_head_pooling_shortcut_conv2d_depthwise_act']['weights']))
        vargface_head_head_pooling_sep1_data_conv2d_pointwise = self.vargface_head_head_pooling_sep1_data_conv2d_pointwise(vargface_head_head_pooling_sep1_data_conv2d_depthwise_act)
        vargface_head_head_pooling_shortcut_conv2d_pointwise = self.vargface_head_head_pooling_shortcut_conv2d_pointwise(vargface_head_head_pooling_shortcut_conv2d_depthwise_act)
        vargface_head_head_pooling_sep1_data_conv2d_pointwise_bn = self.vargface_head_head_pooling_sep1_data_conv2d_pointwise_bn(vargface_head_head_pooling_sep1_data_conv2d_pointwise)
        vargface_head_head_pooling_shortcut_conv2d_pointwise_bn = self.vargface_head_head_pooling_shortcut_conv2d_pointwise_bn(vargface_head_head_pooling_shortcut_conv2d_pointwise)
        vargface_head_head_pooling_sep1_data_conv2d_pointwise_act = F.prelu(vargface_head_head_pooling_sep1_data_conv2d_pointwise_bn, torch.from_numpy(__weights_dict['vargface_head_head_pooling_sep1_data_conv2d_pointwise_act']['weights']))
        vargface_head_head_pooling_sep2_data_conv2d_depthwise_pad = F.pad(vargface_head_head_pooling_sep1_data_conv2d_pointwise_act, (1, 1, 1, 1))
        vargface_head_head_pooling_sep2_data_conv2d_depthwise = self.vargface_head_head_pooling_sep2_data_conv2d_depthwise(vargface_head_head_pooling_sep2_data_conv2d_depthwise_pad)
        vargface_head_head_pooling_sep2_data_conv2d_depthwise_bn = self.vargface_head_head_pooling_sep2_data_conv2d_depthwise_bn(vargface_head_head_pooling_sep2_data_conv2d_depthwise)
        vargface_head_head_pooling_sep2_data_conv2d_depthwise_act = F.prelu(vargface_head_head_pooling_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_head_head_pooling_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_head_head_pooling_sep2_data_conv2d_pointwise = self.vargface_head_head_pooling_sep2_data_conv2d_pointwise(vargface_head_head_pooling_sep2_data_conv2d_depthwise_act)
        vargface_head_head_pooling_sep2_data_conv2d_pointwise_bn = self.vargface_head_head_pooling_sep2_data_conv2d_pointwise_bn(vargface_head_head_pooling_sep2_data_conv2d_pointwise)
        plus0           = vargface_head_head_pooling_sep2_data_conv2d_pointwise_bn + vargface_head_head_pooling_shortcut_conv2d_pointwise_bn
        vargface_head_head_pooling_out_data_act = F.prelu(plus0, torch.from_numpy(__weights_dict['vargface_head_head_pooling_out_data_act']['weights']))
        vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_pad = F.pad(vargface_head_head_pooling_out_data_act, (1, 1, 1, 1))
        vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise = self.vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise(vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_pad)
        vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_pad = F.pad(vargface_head_head_pooling_out_data_act, (1, 1, 1, 1))
        vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise = self.vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise(vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_pad)
        vargface_stage_2_unit_1_shortcut_conv2d_depthwise_pad = F.pad(vargface_head_head_pooling_out_data_act, (1, 1, 1, 1))
        vargface_stage_2_unit_1_shortcut_conv2d_depthwise = self.vargface_stage_2_unit_1_shortcut_conv2d_depthwise(vargface_stage_2_unit_1_shortcut_conv2d_depthwise_pad)
        vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_bn = self.vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_bn(vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise)
        vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_bn = self.vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_bn(vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise)
        vargface_stage_2_unit_1_shortcut_conv2d_depthwise_bn = self.vargface_stage_2_unit_1_shortcut_conv2d_depthwise_bn(vargface_stage_2_unit_1_shortcut_conv2d_depthwise)
        vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_act = F.prelu(vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_act']['weights']))
        vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_act = F.prelu(vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_act']['weights']))
        vargface_stage_2_unit_1_shortcut_conv2d_depthwise_act = F.prelu(vargface_stage_2_unit_1_shortcut_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_2_unit_1_shortcut_conv2d_depthwise_act']['weights']))
        vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise = self.vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise(vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_act)
        vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise = self.vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise(vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_act)
        vargface_stage_2_unit_1_shortcut_conv2d_pointwise = self.vargface_stage_2_unit_1_shortcut_conv2d_pointwise(vargface_stage_2_unit_1_shortcut_conv2d_depthwise_act)
        vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise_bn = self.vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise_bn(vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise)
        vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise_bn = self.vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise_bn(vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise)
        vargface_stage_2_unit_1_shortcut_conv2d_pointwise_bn = self.vargface_stage_2_unit_1_shortcut_conv2d_pointwise_bn(vargface_stage_2_unit_1_shortcut_conv2d_pointwise)
        plus1           = vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise_bn + vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise_bn
        vargface_stage_2_unit_1_sep1_data_act = F.prelu(plus1, torch.from_numpy(__weights_dict['vargface_stage_2_unit_1_sep1_data_act']['weights']))
        vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_2_unit_1_sep1_data_act, (1, 1, 1, 1))
        vargface_stage_2_unit_1_sep2_data_conv2d_depthwise = self.vargface_stage_2_unit_1_sep2_data_conv2d_depthwise(vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_pad)
        vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_bn = self.vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_bn(vargface_stage_2_unit_1_sep2_data_conv2d_depthwise)
        vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_2_unit_1_sep2_data_conv2d_pointwise = self.vargface_stage_2_unit_1_sep2_data_conv2d_pointwise(vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_act)
        vargface_stage_2_unit_1_sep2_data_conv2d_pointwise_bn = self.vargface_stage_2_unit_1_sep2_data_conv2d_pointwise_bn(vargface_stage_2_unit_1_sep2_data_conv2d_pointwise)
        plus2           = vargface_stage_2_unit_1_sep2_data_conv2d_pointwise_bn + vargface_stage_2_unit_1_shortcut_conv2d_pointwise_bn
        vargface_stage_2_unit_1_out_data_act = F.prelu(plus2, torch.from_numpy(__weights_dict['vargface_stage_2_unit_1_out_data_act']['weights']))
        vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_pad = F.pad(vargface_stage_2_unit_1_out_data_act, (1, 1, 1, 1))
        vargface_stage_2_unit_2_sep1_data_conv2d_depthwise = self.vargface_stage_2_unit_2_sep1_data_conv2d_depthwise(vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_pad)
        vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_bn = self.vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_bn(vargface_stage_2_unit_2_sep1_data_conv2d_depthwise)
        vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_act = F.prelu(vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_act']['weights']))
        vargface_stage_2_unit_2_sep1_data_conv2d_pointwise = self.vargface_stage_2_unit_2_sep1_data_conv2d_pointwise(vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_act)
        vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_bn = self.vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_bn(vargface_stage_2_unit_2_sep1_data_conv2d_pointwise)
        vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_act = F.prelu(vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_bn, torch.from_numpy(__weights_dict['vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_act']['weights']))
        vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_act, (1, 1, 1, 1))
        vargface_stage_2_unit_2_sep2_data_conv2d_depthwise = self.vargface_stage_2_unit_2_sep2_data_conv2d_depthwise(vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_pad)
        vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_bn = self.vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_bn(vargface_stage_2_unit_2_sep2_data_conv2d_depthwise)
        vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_2_unit_2_sep2_data_conv2d_pointwise = self.vargface_stage_2_unit_2_sep2_data_conv2d_pointwise(vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_act)
        vargface_stage_2_unit_2_sep2_data_conv2d_pointwise_bn = self.vargface_stage_2_unit_2_sep2_data_conv2d_pointwise_bn(vargface_stage_2_unit_2_sep2_data_conv2d_pointwise)
        plus3           = vargface_stage_2_unit_2_sep2_data_conv2d_pointwise_bn + vargface_stage_2_unit_1_out_data_act
        vargface_stage_2_unit_2_out_data_act = F.prelu(plus3, torch.from_numpy(__weights_dict['vargface_stage_2_unit_2_out_data_act']['weights']))
        vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_pad = F.pad(vargface_stage_2_unit_2_out_data_act, (1, 1, 1, 1))
        vargface_stage_2_unit_3_sep1_data_conv2d_depthwise = self.vargface_stage_2_unit_3_sep1_data_conv2d_depthwise(vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_pad)
        vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_bn = self.vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_bn(vargface_stage_2_unit_3_sep1_data_conv2d_depthwise)
        vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_act = F.prelu(vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_act']['weights']))
        vargface_stage_2_unit_3_sep1_data_conv2d_pointwise = self.vargface_stage_2_unit_3_sep1_data_conv2d_pointwise(vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_act)
        vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_bn = self.vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_bn(vargface_stage_2_unit_3_sep1_data_conv2d_pointwise)
        vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_act = F.prelu(vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_bn, torch.from_numpy(__weights_dict['vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_act']['weights']))
        vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_act, (1, 1, 1, 1))
        vargface_stage_2_unit_3_sep2_data_conv2d_depthwise = self.vargface_stage_2_unit_3_sep2_data_conv2d_depthwise(vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_pad)
        vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_bn = self.vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_bn(vargface_stage_2_unit_3_sep2_data_conv2d_depthwise)
        vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_2_unit_3_sep2_data_conv2d_pointwise = self.vargface_stage_2_unit_3_sep2_data_conv2d_pointwise(vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_act)
        vargface_stage_2_unit_3_sep2_data_conv2d_pointwise_bn = self.vargface_stage_2_unit_3_sep2_data_conv2d_pointwise_bn(vargface_stage_2_unit_3_sep2_data_conv2d_pointwise)
        plus4           = vargface_stage_2_unit_3_sep2_data_conv2d_pointwise_bn + vargface_stage_2_unit_2_out_data_act
        vargface_stage_2_unit_3_out_data_act = F.prelu(plus4, torch.from_numpy(__weights_dict['vargface_stage_2_unit_3_out_data_act']['weights']))
        vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_pad = F.pad(vargface_stage_2_unit_3_out_data_act, (1, 1, 1, 1))
        vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise = self.vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise(vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_pad)
        vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_pad = F.pad(vargface_stage_2_unit_3_out_data_act, (1, 1, 1, 1))
        vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise = self.vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise(vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_pad)
        vargface_stage_3_unit_1_shortcut_conv2d_depthwise_pad = F.pad(vargface_stage_2_unit_3_out_data_act, (1, 1, 1, 1))
        vargface_stage_3_unit_1_shortcut_conv2d_depthwise = self.vargface_stage_3_unit_1_shortcut_conv2d_depthwise(vargface_stage_3_unit_1_shortcut_conv2d_depthwise_pad)
        vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_bn = self.vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_bn(vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise)
        vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_bn = self.vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_bn(vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise)
        vargface_stage_3_unit_1_shortcut_conv2d_depthwise_bn = self.vargface_stage_3_unit_1_shortcut_conv2d_depthwise_bn(vargface_stage_3_unit_1_shortcut_conv2d_depthwise)
        vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_1_shortcut_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_1_shortcut_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_1_shortcut_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise = self.vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise(vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_act)
        vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise = self.vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise(vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_act)
        vargface_stage_3_unit_1_shortcut_conv2d_pointwise = self.vargface_stage_3_unit_1_shortcut_conv2d_pointwise(vargface_stage_3_unit_1_shortcut_conv2d_depthwise_act)
        vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise_bn = self.vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise_bn(vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise)
        vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise_bn = self.vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise_bn(vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise)
        vargface_stage_3_unit_1_shortcut_conv2d_pointwise_bn = self.vargface_stage_3_unit_1_shortcut_conv2d_pointwise_bn(vargface_stage_3_unit_1_shortcut_conv2d_pointwise)
        plus5           = vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise_bn + vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise_bn
        vargface_stage_3_unit_1_sep1_data_act = F.prelu(plus5, torch.from_numpy(__weights_dict['vargface_stage_3_unit_1_sep1_data_act']['weights']))
        vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_1_sep1_data_act, (1, 1, 1, 1))
        vargface_stage_3_unit_1_sep2_data_conv2d_depthwise = self.vargface_stage_3_unit_1_sep2_data_conv2d_depthwise(vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_pad)
        vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_bn = self.vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_bn(vargface_stage_3_unit_1_sep2_data_conv2d_depthwise)
        vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_1_sep2_data_conv2d_pointwise = self.vargface_stage_3_unit_1_sep2_data_conv2d_pointwise(vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_act)
        vargface_stage_3_unit_1_sep2_data_conv2d_pointwise_bn = self.vargface_stage_3_unit_1_sep2_data_conv2d_pointwise_bn(vargface_stage_3_unit_1_sep2_data_conv2d_pointwise)
        plus6           = vargface_stage_3_unit_1_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_1_shortcut_conv2d_pointwise_bn
        vargface_stage_3_unit_1_out_data_act = F.prelu(plus6, torch.from_numpy(__weights_dict['vargface_stage_3_unit_1_out_data_act']['weights']))
        vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_1_out_data_act, (1, 1, 1, 1))
        vargface_stage_3_unit_2_sep1_data_conv2d_depthwise = self.vargface_stage_3_unit_2_sep1_data_conv2d_depthwise(vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_pad)
        vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_bn = self.vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_bn(vargface_stage_3_unit_2_sep1_data_conv2d_depthwise)
        vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_2_sep1_data_conv2d_pointwise = self.vargface_stage_3_unit_2_sep1_data_conv2d_pointwise(vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_act)
        vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_bn = self.vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_bn(vargface_stage_3_unit_2_sep1_data_conv2d_pointwise)
        vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_act = F.prelu(vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_act']['weights']))
        vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_act, (1, 1, 1, 1))
        vargface_stage_3_unit_2_sep2_data_conv2d_depthwise = self.vargface_stage_3_unit_2_sep2_data_conv2d_depthwise(vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_pad)
        vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_bn = self.vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_bn(vargface_stage_3_unit_2_sep2_data_conv2d_depthwise)
        vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_2_sep2_data_conv2d_pointwise = self.vargface_stage_3_unit_2_sep2_data_conv2d_pointwise(vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_act)
        vargface_stage_3_unit_2_sep2_data_conv2d_pointwise_bn = self.vargface_stage_3_unit_2_sep2_data_conv2d_pointwise_bn(vargface_stage_3_unit_2_sep2_data_conv2d_pointwise)
        plus7           = vargface_stage_3_unit_2_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_1_out_data_act
        vargface_stage_3_unit_2_out_data_act = F.prelu(plus7, torch.from_numpy(__weights_dict['vargface_stage_3_unit_2_out_data_act']['weights']))
        vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_2_out_data_act, (1, 1, 1, 1))
        vargface_stage_3_unit_3_sep1_data_conv2d_depthwise = self.vargface_stage_3_unit_3_sep1_data_conv2d_depthwise(vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_pad)
        vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_bn = self.vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_bn(vargface_stage_3_unit_3_sep1_data_conv2d_depthwise)
        vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_3_sep1_data_conv2d_pointwise = self.vargface_stage_3_unit_3_sep1_data_conv2d_pointwise(vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_act)
        vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_bn = self.vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_bn(vargface_stage_3_unit_3_sep1_data_conv2d_pointwise)
        vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_act = F.prelu(vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_act']['weights']))
        vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_act, (1, 1, 1, 1))
        vargface_stage_3_unit_3_sep2_data_conv2d_depthwise = self.vargface_stage_3_unit_3_sep2_data_conv2d_depthwise(vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_pad)
        vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_bn = self.vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_bn(vargface_stage_3_unit_3_sep2_data_conv2d_depthwise)
        vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_3_sep2_data_conv2d_pointwise = self.vargface_stage_3_unit_3_sep2_data_conv2d_pointwise(vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_act)
        vargface_stage_3_unit_3_sep2_data_conv2d_pointwise_bn = self.vargface_stage_3_unit_3_sep2_data_conv2d_pointwise_bn(vargface_stage_3_unit_3_sep2_data_conv2d_pointwise)
        plus8           = vargface_stage_3_unit_3_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_2_out_data_act
        vargface_stage_3_unit_3_out_data_act = F.prelu(plus8, torch.from_numpy(__weights_dict['vargface_stage_3_unit_3_out_data_act']['weights']))
        vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_3_out_data_act, (1, 1, 1, 1))
        vargface_stage_3_unit_4_sep1_data_conv2d_depthwise = self.vargface_stage_3_unit_4_sep1_data_conv2d_depthwise(vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_pad)
        vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_bn = self.vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_bn(vargface_stage_3_unit_4_sep1_data_conv2d_depthwise)
        vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_4_sep1_data_conv2d_pointwise = self.vargface_stage_3_unit_4_sep1_data_conv2d_pointwise(vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_act)
        vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_bn = self.vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_bn(vargface_stage_3_unit_4_sep1_data_conv2d_pointwise)
        vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_act = F.prelu(vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_act']['weights']))
        vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_act, (1, 1, 1, 1))
        vargface_stage_3_unit_4_sep2_data_conv2d_depthwise = self.vargface_stage_3_unit_4_sep2_data_conv2d_depthwise(vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_pad)
        vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_bn = self.vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_bn(vargface_stage_3_unit_4_sep2_data_conv2d_depthwise)
        vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_4_sep2_data_conv2d_pointwise = self.vargface_stage_3_unit_4_sep2_data_conv2d_pointwise(vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_act)
        vargface_stage_3_unit_4_sep2_data_conv2d_pointwise_bn = self.vargface_stage_3_unit_4_sep2_data_conv2d_pointwise_bn(vargface_stage_3_unit_4_sep2_data_conv2d_pointwise)
        plus9           = vargface_stage_3_unit_4_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_3_out_data_act
        vargface_stage_3_unit_4_out_data_act = F.prelu(plus9, torch.from_numpy(__weights_dict['vargface_stage_3_unit_4_out_data_act']['weights']))
        vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_4_out_data_act, (1, 1, 1, 1))
        vargface_stage_3_unit_5_sep1_data_conv2d_depthwise = self.vargface_stage_3_unit_5_sep1_data_conv2d_depthwise(vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_pad)
        vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_bn = self.vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_bn(vargface_stage_3_unit_5_sep1_data_conv2d_depthwise)
        vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_5_sep1_data_conv2d_pointwise = self.vargface_stage_3_unit_5_sep1_data_conv2d_pointwise(vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_act)
        vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_bn = self.vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_bn(vargface_stage_3_unit_5_sep1_data_conv2d_pointwise)
        vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_act = F.prelu(vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_act']['weights']))
        vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_act, (1, 1, 1, 1))
        vargface_stage_3_unit_5_sep2_data_conv2d_depthwise = self.vargface_stage_3_unit_5_sep2_data_conv2d_depthwise(vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_pad)
        vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_bn = self.vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_bn(vargface_stage_3_unit_5_sep2_data_conv2d_depthwise)
        vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_5_sep2_data_conv2d_pointwise = self.vargface_stage_3_unit_5_sep2_data_conv2d_pointwise(vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_act)
        vargface_stage_3_unit_5_sep2_data_conv2d_pointwise_bn = self.vargface_stage_3_unit_5_sep2_data_conv2d_pointwise_bn(vargface_stage_3_unit_5_sep2_data_conv2d_pointwise)
        plus10          = vargface_stage_3_unit_5_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_4_out_data_act
        vargface_stage_3_unit_5_out_data_act = F.prelu(plus10, torch.from_numpy(__weights_dict['vargface_stage_3_unit_5_out_data_act']['weights']))
        vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_5_out_data_act, (1, 1, 1, 1))
        vargface_stage_3_unit_6_sep1_data_conv2d_depthwise = self.vargface_stage_3_unit_6_sep1_data_conv2d_depthwise(vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_pad)
        vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_bn = self.vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_bn(vargface_stage_3_unit_6_sep1_data_conv2d_depthwise)
        vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_6_sep1_data_conv2d_pointwise = self.vargface_stage_3_unit_6_sep1_data_conv2d_pointwise(vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_act)
        vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_bn = self.vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_bn(vargface_stage_3_unit_6_sep1_data_conv2d_pointwise)
        vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_act = F.prelu(vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_act']['weights']))
        vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_act, (1, 1, 1, 1))
        vargface_stage_3_unit_6_sep2_data_conv2d_depthwise = self.vargface_stage_3_unit_6_sep2_data_conv2d_depthwise(vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_pad)
        vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_bn = self.vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_bn(vargface_stage_3_unit_6_sep2_data_conv2d_depthwise)
        vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_6_sep2_data_conv2d_pointwise = self.vargface_stage_3_unit_6_sep2_data_conv2d_pointwise(vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_act)
        vargface_stage_3_unit_6_sep2_data_conv2d_pointwise_bn = self.vargface_stage_3_unit_6_sep2_data_conv2d_pointwise_bn(vargface_stage_3_unit_6_sep2_data_conv2d_pointwise)
        plus11          = vargface_stage_3_unit_6_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_5_out_data_act
        vargface_stage_3_unit_6_out_data_act = F.prelu(plus11, torch.from_numpy(__weights_dict['vargface_stage_3_unit_6_out_data_act']['weights']))
        vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_6_out_data_act, (1, 1, 1, 1))
        vargface_stage_3_unit_7_sep1_data_conv2d_depthwise = self.vargface_stage_3_unit_7_sep1_data_conv2d_depthwise(vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_pad)
        vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_bn = self.vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_bn(vargface_stage_3_unit_7_sep1_data_conv2d_depthwise)
        vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_7_sep1_data_conv2d_pointwise = self.vargface_stage_3_unit_7_sep1_data_conv2d_pointwise(vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_act)
        vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_bn = self.vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_bn(vargface_stage_3_unit_7_sep1_data_conv2d_pointwise)
        vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_act = F.prelu(vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_act']['weights']))
        vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_act, (1, 1, 1, 1))
        vargface_stage_3_unit_7_sep2_data_conv2d_depthwise = self.vargface_stage_3_unit_7_sep2_data_conv2d_depthwise(vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_pad)
        vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_bn = self.vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_bn(vargface_stage_3_unit_7_sep2_data_conv2d_depthwise)
        vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_3_unit_7_sep2_data_conv2d_pointwise = self.vargface_stage_3_unit_7_sep2_data_conv2d_pointwise(vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_act)
        vargface_stage_3_unit_7_sep2_data_conv2d_pointwise_bn = self.vargface_stage_3_unit_7_sep2_data_conv2d_pointwise_bn(vargface_stage_3_unit_7_sep2_data_conv2d_pointwise)
        plus12          = vargface_stage_3_unit_7_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_6_out_data_act
        vargface_stage_3_unit_7_out_data_act = F.prelu(plus12, torch.from_numpy(__weights_dict['vargface_stage_3_unit_7_out_data_act']['weights']))
        vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_7_out_data_act, (1, 1, 1, 1))
        vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise = self.vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise(vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_pad)
        vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_7_out_data_act, (1, 1, 1, 1))
        vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise = self.vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise(vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_pad)
        vargface_stage_4_unit_1_shortcut_conv2d_depthwise_pad = F.pad(vargface_stage_3_unit_7_out_data_act, (1, 1, 1, 1))
        vargface_stage_4_unit_1_shortcut_conv2d_depthwise = self.vargface_stage_4_unit_1_shortcut_conv2d_depthwise(vargface_stage_4_unit_1_shortcut_conv2d_depthwise_pad)
        vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_bn = self.vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_bn(vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise)
        vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_bn = self.vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_bn(vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise)
        vargface_stage_4_unit_1_shortcut_conv2d_depthwise_bn = self.vargface_stage_4_unit_1_shortcut_conv2d_depthwise_bn(vargface_stage_4_unit_1_shortcut_conv2d_depthwise)
        vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_act = F.prelu(vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_act']['weights']))
        vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_act = F.prelu(vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_act']['weights']))
        vargface_stage_4_unit_1_shortcut_conv2d_depthwise_act = F.prelu(vargface_stage_4_unit_1_shortcut_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_4_unit_1_shortcut_conv2d_depthwise_act']['weights']))
        vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise = self.vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise(vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_act)
        vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise = self.vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise(vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_act)
        vargface_stage_4_unit_1_shortcut_conv2d_pointwise = self.vargface_stage_4_unit_1_shortcut_conv2d_pointwise(vargface_stage_4_unit_1_shortcut_conv2d_depthwise_act)
        vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise_bn = self.vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise_bn(vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise)
        vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise_bn = self.vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise_bn(vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise)
        vargface_stage_4_unit_1_shortcut_conv2d_pointwise_bn = self.vargface_stage_4_unit_1_shortcut_conv2d_pointwise_bn(vargface_stage_4_unit_1_shortcut_conv2d_pointwise)
        plus13          = vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise_bn + vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise_bn
        vargface_stage_4_unit_1_sep1_data_act = F.prelu(plus13, torch.from_numpy(__weights_dict['vargface_stage_4_unit_1_sep1_data_act']['weights']))
        vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_4_unit_1_sep1_data_act, (1, 1, 1, 1))
        vargface_stage_4_unit_1_sep2_data_conv2d_depthwise = self.vargface_stage_4_unit_1_sep2_data_conv2d_depthwise(vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_pad)
        vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_bn = self.vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_bn(vargface_stage_4_unit_1_sep2_data_conv2d_depthwise)
        vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_4_unit_1_sep2_data_conv2d_pointwise = self.vargface_stage_4_unit_1_sep2_data_conv2d_pointwise(vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_act)
        vargface_stage_4_unit_1_sep2_data_conv2d_pointwise_bn = self.vargface_stage_4_unit_1_sep2_data_conv2d_pointwise_bn(vargface_stage_4_unit_1_sep2_data_conv2d_pointwise)
        plus14          = vargface_stage_4_unit_1_sep2_data_conv2d_pointwise_bn + vargface_stage_4_unit_1_shortcut_conv2d_pointwise_bn
        vargface_stage_4_unit_1_out_data_act = F.prelu(plus14, torch.from_numpy(__weights_dict['vargface_stage_4_unit_1_out_data_act']['weights']))
        vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_pad = F.pad(vargface_stage_4_unit_1_out_data_act, (1, 1, 1, 1))
        vargface_stage_4_unit_2_sep1_data_conv2d_depthwise = self.vargface_stage_4_unit_2_sep1_data_conv2d_depthwise(vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_pad)
        vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_bn = self.vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_bn(vargface_stage_4_unit_2_sep1_data_conv2d_depthwise)
        vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_act = F.prelu(vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_act']['weights']))
        vargface_stage_4_unit_2_sep1_data_conv2d_pointwise = self.vargface_stage_4_unit_2_sep1_data_conv2d_pointwise(vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_act)
        vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_bn = self.vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_bn(vargface_stage_4_unit_2_sep1_data_conv2d_pointwise)
        vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_act = F.prelu(vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_bn, torch.from_numpy(__weights_dict['vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_act']['weights']))
        vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_act, (1, 1, 1, 1))
        vargface_stage_4_unit_2_sep2_data_conv2d_depthwise = self.vargface_stage_4_unit_2_sep2_data_conv2d_depthwise(vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_pad)
        vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_bn = self.vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_bn(vargface_stage_4_unit_2_sep2_data_conv2d_depthwise)
        vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_4_unit_2_sep2_data_conv2d_pointwise = self.vargface_stage_4_unit_2_sep2_data_conv2d_pointwise(vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_act)
        vargface_stage_4_unit_2_sep2_data_conv2d_pointwise_bn = self.vargface_stage_4_unit_2_sep2_data_conv2d_pointwise_bn(vargface_stage_4_unit_2_sep2_data_conv2d_pointwise)
        plus15          = vargface_stage_4_unit_2_sep2_data_conv2d_pointwise_bn + vargface_stage_4_unit_1_out_data_act
        vargface_stage_4_unit_2_out_data_act = F.prelu(plus15, torch.from_numpy(__weights_dict['vargface_stage_4_unit_2_out_data_act']['weights']))
        vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_pad = F.pad(vargface_stage_4_unit_2_out_data_act, (1, 1, 1, 1))
        vargface_stage_4_unit_3_sep1_data_conv2d_depthwise = self.vargface_stage_4_unit_3_sep1_data_conv2d_depthwise(vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_pad)
        vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_bn = self.vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_bn(vargface_stage_4_unit_3_sep1_data_conv2d_depthwise)
        vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_act = F.prelu(vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_act']['weights']))
        vargface_stage_4_unit_3_sep1_data_conv2d_pointwise = self.vargface_stage_4_unit_3_sep1_data_conv2d_pointwise(vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_act)
        vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_bn = self.vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_bn(vargface_stage_4_unit_3_sep1_data_conv2d_pointwise)
        vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_act = F.prelu(vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_bn, torch.from_numpy(__weights_dict['vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_act']['weights']))
        vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_act, (1, 1, 1, 1))
        vargface_stage_4_unit_3_sep2_data_conv2d_depthwise = self.vargface_stage_4_unit_3_sep2_data_conv2d_depthwise(vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_pad)
        vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_bn = self.vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_bn(vargface_stage_4_unit_3_sep2_data_conv2d_depthwise)
        vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_4_unit_3_sep2_data_conv2d_pointwise = self.vargface_stage_4_unit_3_sep2_data_conv2d_pointwise(vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_act)
        vargface_stage_4_unit_3_sep2_data_conv2d_pointwise_bn = self.vargface_stage_4_unit_3_sep2_data_conv2d_pointwise_bn(vargface_stage_4_unit_3_sep2_data_conv2d_pointwise)
        plus16          = vargface_stage_4_unit_3_sep2_data_conv2d_pointwise_bn + vargface_stage_4_unit_2_out_data_act
        vargface_stage_4_unit_3_out_data_act = F.prelu(plus16, torch.from_numpy(__weights_dict['vargface_stage_4_unit_3_out_data_act']['weights']))
        vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_pad = F.pad(vargface_stage_4_unit_3_out_data_act, (1, 1, 1, 1))
        vargface_stage_4_unit_4_sep1_data_conv2d_depthwise = self.vargface_stage_4_unit_4_sep1_data_conv2d_depthwise(vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_pad)
        vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_bn = self.vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_bn(vargface_stage_4_unit_4_sep1_data_conv2d_depthwise)
        vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_act = F.prelu(vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_act']['weights']))
        vargface_stage_4_unit_4_sep1_data_conv2d_pointwise = self.vargface_stage_4_unit_4_sep1_data_conv2d_pointwise(vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_act)
        vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_bn = self.vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_bn(vargface_stage_4_unit_4_sep1_data_conv2d_pointwise)
        vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_act = F.prelu(vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_bn, torch.from_numpy(__weights_dict['vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_act']['weights']))
        vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_pad = F.pad(vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_act, (1, 1, 1, 1))
        vargface_stage_4_unit_4_sep2_data_conv2d_depthwise = self.vargface_stage_4_unit_4_sep2_data_conv2d_depthwise(vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_pad)
        vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_bn = self.vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_bn(vargface_stage_4_unit_4_sep2_data_conv2d_depthwise)
        vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_act = F.prelu(vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_bn, torch.from_numpy(__weights_dict['vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_act']['weights']))
        vargface_stage_4_unit_4_sep2_data_conv2d_pointwise = self.vargface_stage_4_unit_4_sep2_data_conv2d_pointwise(vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_act)
        vargface_stage_4_unit_4_sep2_data_conv2d_pointwise_bn = self.vargface_stage_4_unit_4_sep2_data_conv2d_pointwise_bn(vargface_stage_4_unit_4_sep2_data_conv2d_pointwise)
        plus17          = vargface_stage_4_unit_4_sep2_data_conv2d_pointwise_bn + vargface_stage_4_unit_3_out_data_act
        vargface_stage_4_unit_4_out_data_act = F.prelu(plus17, torch.from_numpy(__weights_dict['vargface_stage_4_unit_4_out_data_act']['weights']))
        embed_convx     = self.embed_convx(vargface_stage_4_unit_4_out_data_act)
        embed_convx_bn  = self.embed_convx_bn(embed_convx)
        embed_convx_act = F.prelu(embed_convx_bn, torch.from_numpy(__weights_dict['embed_convx_act']['weights']))
        embed_convx_depthwise = self.embed_convx_depthwise(embed_convx_act)
        embed_convx_depthwise_bn = self.embed_convx_depthwise_bn(embed_convx_depthwise)
        embed_convx_pointwise = self.embed_convx_pointwise(embed_convx_depthwise_bn)
        embed_convx_pointwise_bn = self.embed_convx_pointwise_bn(embed_convx_pointwise)
        embed_convx_pointwise_act = F.prelu(embed_convx_pointwise_bn, torch.from_numpy(__weights_dict['embed_convx_pointwise_act']['weights']))
        pre_fc1         = self.pre_fc1(embed_convx_pointwise_act.view(embed_convx_pointwise_act.size(0), -1))
        fc1             = self.fc1(pre_fc1)
        return fc1


    @staticmethod
    def __conv(dim, name, **kwargs):
        if   dim == 1:  layer = nn.Conv1d(**kwargs)
        elif dim == 2:  layer = nn.Conv2d(**kwargs)
        elif dim == 3:  layer = nn.Conv3d(**kwargs)
        else:           raise NotImplementedError()

        layer.state_dict()['weight'].copy_(torch.from_numpy(__weights_dict[name]['weights']))
        if 'bias' in __weights_dict[name]:
            layer.state_dict()['bias'].copy_(torch.from_numpy(__weights_dict[name]['bias']))
        return layer

    @staticmethod
    def __batch_normalization(dim, name, **kwargs):
        if   dim == 0 or dim == 1:  layer = nn.BatchNorm1d(**kwargs)
        elif dim == 2:  layer = nn.BatchNorm2d(**kwargs)
        elif dim == 3:  layer = nn.BatchNorm3d(**kwargs)
        else:           raise NotImplementedError()

        if 'scale' in __weights_dict[name]:
            layer.state_dict()['weight'].copy_(torch.from_numpy(__weights_dict[name]['scale']))
        else:
            layer.weight.data.fill_(1)

        if 'bias' in __weights_dict[name]:
            layer.state_dict()['bias'].copy_(torch.from_numpy(__weights_dict[name]['bias']))
        else:
            layer.bias.data.fill_(0)

        layer.state_dict()['running_mean'].copy_(torch.from_numpy(__weights_dict[name]['mean']))
        layer.state_dict()['running_var'].copy_(torch.from_numpy(__weights_dict[name]['var']))
        return layer

    @staticmethod
    def __dense(name, **kwargs):
        layer = nn.Linear(**kwargs)
        layer.state_dict()['weight'].copy_(torch.from_numpy(__weights_dict[name]['weights']))
        if 'bias' in __weights_dict[name]:
            layer.state_dict()['bias'].copy_(torch.from_numpy(__weights_dict[name]['bias']))
        return layer

