import tensorflow as tf

__weights_dict = dict()

is_train = False

def load_weights(weight_file):
    import numpy as np

    if weight_file == None:
        return

    try:
        weights_dict = np.load(weight_file).item()
    except:
        weights_dict = np.load(weight_file, encoding='bytes').item()

    return weights_dict


def KitModel(weight_file = None):
    global __weights_dict
    __weights_dict = load_weights(weight_file)

    data            = tf.placeholder(tf.float32, shape = (None, 112, 112, 3), name = 'data')
    minusscalar0_second = tf.constant(__weights_dict['minusscalar0_second']['value'], dtype=tf.float32, name='minusscalar0_second')
    mulscalar0_second = tf.constant(__weights_dict['mulscalar0_second']['value'], dtype=tf.float32, name='mulscalar0_second')
    minusscalar0    = data - minusscalar0_second
    mulscalar0      = minusscalar0 * mulscalar0_second
    vargface_head_conv1_pad = tf.pad(mulscalar0, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_head_conv1 = convolution(vargface_head_conv1_pad, group=1, strides=[1, 1], padding='VALID', name='vargface_head_conv1')
    vargface_head_conv1_bn = batch_normalization(vargface_head_conv1, variance_epsilon=1.9999999494757503e-05, name='vargface_head_conv1_bn')
    vargface_head_conv1_act = prelu(vargface_head_conv1_bn, name='vargface_head_conv1_act')
    vargface_head_head_pooling_sep1_data_conv2d_depthwise_pad = tf.pad(vargface_head_conv1_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_head_head_pooling_sep1_data_conv2d_depthwise = convolution(vargface_head_head_pooling_sep1_data_conv2d_depthwise_pad, group=5, strides=[2, 2], padding='VALID', name='vargface_head_head_pooling_sep1_data_conv2d_depthwise')
    vargface_head_head_pooling_shortcut_conv2d_depthwise_pad = tf.pad(vargface_head_conv1_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_head_head_pooling_shortcut_conv2d_depthwise = convolution(vargface_head_head_pooling_shortcut_conv2d_depthwise_pad, group=5, strides=[2, 2], padding='VALID', name='vargface_head_head_pooling_shortcut_conv2d_depthwise')
    vargface_head_head_pooling_sep1_data_conv2d_depthwise_bn = batch_normalization(vargface_head_head_pooling_sep1_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_head_head_pooling_sep1_data_conv2d_depthwise_bn')
    vargface_head_head_pooling_shortcut_conv2d_depthwise_bn = batch_normalization(vargface_head_head_pooling_shortcut_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_head_head_pooling_shortcut_conv2d_depthwise_bn')
    vargface_head_head_pooling_sep1_data_conv2d_depthwise_act = prelu(vargface_head_head_pooling_sep1_data_conv2d_depthwise_bn, name='vargface_head_head_pooling_sep1_data_conv2d_depthwise_act')
    vargface_head_head_pooling_shortcut_conv2d_depthwise_act = prelu(vargface_head_head_pooling_shortcut_conv2d_depthwise_bn, name='vargface_head_head_pooling_shortcut_conv2d_depthwise_act')
    vargface_head_head_pooling_sep1_data_conv2d_pointwise = convolution(vargface_head_head_pooling_sep1_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_head_head_pooling_sep1_data_conv2d_pointwise')
    vargface_head_head_pooling_shortcut_conv2d_pointwise = convolution(vargface_head_head_pooling_shortcut_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_head_head_pooling_shortcut_conv2d_pointwise')
    vargface_head_head_pooling_sep1_data_conv2d_pointwise_bn = batch_normalization(vargface_head_head_pooling_sep1_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_head_head_pooling_sep1_data_conv2d_pointwise_bn')
    vargface_head_head_pooling_shortcut_conv2d_pointwise_bn = batch_normalization(vargface_head_head_pooling_shortcut_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_head_head_pooling_shortcut_conv2d_pointwise_bn')
    vargface_head_head_pooling_sep1_data_conv2d_pointwise_act = prelu(vargface_head_head_pooling_sep1_data_conv2d_pointwise_bn, name='vargface_head_head_pooling_sep1_data_conv2d_pointwise_act')
    vargface_head_head_pooling_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_head_head_pooling_sep1_data_conv2d_pointwise_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_head_head_pooling_sep2_data_conv2d_depthwise = convolution(vargface_head_head_pooling_sep2_data_conv2d_depthwise_pad, group=5, strides=[1, 1], padding='VALID', name='vargface_head_head_pooling_sep2_data_conv2d_depthwise')
    vargface_head_head_pooling_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_head_head_pooling_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_head_head_pooling_sep2_data_conv2d_depthwise_bn')
    vargface_head_head_pooling_sep2_data_conv2d_depthwise_act = prelu(vargface_head_head_pooling_sep2_data_conv2d_depthwise_bn, name='vargface_head_head_pooling_sep2_data_conv2d_depthwise_act')
    vargface_head_head_pooling_sep2_data_conv2d_pointwise = convolution(vargface_head_head_pooling_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_head_head_pooling_sep2_data_conv2d_pointwise')
    vargface_head_head_pooling_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_head_head_pooling_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_head_head_pooling_sep2_data_conv2d_pointwise_bn')
    plus0           = vargface_head_head_pooling_sep2_data_conv2d_pointwise_bn + vargface_head_head_pooling_shortcut_conv2d_pointwise_bn
    vargface_head_head_pooling_out_data_act = prelu(plus0, name='vargface_head_head_pooling_out_data_act')
    vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_pad = tf.pad(vargface_head_head_pooling_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise = convolution(vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_pad, group=5, strides=[2, 2], padding='VALID', name='vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise')
    vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_pad = tf.pad(vargface_head_head_pooling_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise = convolution(vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_pad, group=5, strides=[2, 2], padding='VALID', name='vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise')
    vargface_stage_2_unit_1_shortcut_conv2d_depthwise_pad = tf.pad(vargface_head_head_pooling_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_2_unit_1_shortcut_conv2d_depthwise = convolution(vargface_stage_2_unit_1_shortcut_conv2d_depthwise_pad, group=5, strides=[2, 2], padding='VALID', name='vargface_stage_2_unit_1_shortcut_conv2d_depthwise')
    vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_bn = batch_normalization(vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_bn')
    vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_bn = batch_normalization(vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_bn')
    vargface_stage_2_unit_1_shortcut_conv2d_depthwise_bn = batch_normalization(vargface_stage_2_unit_1_shortcut_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_1_shortcut_conv2d_depthwise_bn')
    vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_act = prelu(vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_bn, name='vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_act')
    vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_act = prelu(vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_bn, name='vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_act')
    vargface_stage_2_unit_1_shortcut_conv2d_depthwise_act = prelu(vargface_stage_2_unit_1_shortcut_conv2d_depthwise_bn, name='vargface_stage_2_unit_1_shortcut_conv2d_depthwise_act')
    vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise = convolution(vargface_stage_2_unit_1_sep1_data_branch_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise')
    vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise = convolution(vargface_stage_2_unit_1_sep2_data_branch_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise')
    vargface_stage_2_unit_1_shortcut_conv2d_pointwise = convolution(vargface_stage_2_unit_1_shortcut_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_2_unit_1_shortcut_conv2d_pointwise')
    vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise_bn = batch_normalization(vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise_bn')
    vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise_bn = batch_normalization(vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise_bn')
    vargface_stage_2_unit_1_shortcut_conv2d_pointwise_bn = batch_normalization(vargface_stage_2_unit_1_shortcut_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_1_shortcut_conv2d_pointwise_bn')
    plus1           = vargface_stage_2_unit_1_sep1_data_branch_conv2d_pointwise_bn + vargface_stage_2_unit_1_sep2_data_branch_conv2d_pointwise_bn
    vargface_stage_2_unit_1_sep1_data_act = prelu(plus1, name='vargface_stage_2_unit_1_sep1_data_act')
    vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_2_unit_1_sep1_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_2_unit_1_sep2_data_conv2d_depthwise = convolution(vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_pad, group=10, strides=[1, 1], padding='VALID', name='vargface_stage_2_unit_1_sep2_data_conv2d_depthwise')
    vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_2_unit_1_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_bn')
    vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_bn, name='vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_act')
    vargface_stage_2_unit_1_sep2_data_conv2d_pointwise = convolution(vargface_stage_2_unit_1_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_2_unit_1_sep2_data_conv2d_pointwise')
    vargface_stage_2_unit_1_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_2_unit_1_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_1_sep2_data_conv2d_pointwise_bn')
    plus2           = vargface_stage_2_unit_1_sep2_data_conv2d_pointwise_bn + vargface_stage_2_unit_1_shortcut_conv2d_pointwise_bn
    vargface_stage_2_unit_1_out_data_act = prelu(plus2, name='vargface_stage_2_unit_1_out_data_act')
    vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_pad = tf.pad(vargface_stage_2_unit_1_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_2_unit_2_sep1_data_conv2d_depthwise = convolution(vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_pad, group=10, strides=[1, 1], padding='VALID', name='vargface_stage_2_unit_2_sep1_data_conv2d_depthwise')
    vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_2_unit_2_sep1_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_bn')
    vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_act = prelu(vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_bn, name='vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_act')
    vargface_stage_2_unit_2_sep1_data_conv2d_pointwise = convolution(vargface_stage_2_unit_2_sep1_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_2_unit_2_sep1_data_conv2d_pointwise')
    vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_2_unit_2_sep1_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_bn')
    vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_act = prelu(vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_bn, name='vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_act')
    vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_2_unit_2_sep1_data_conv2d_pointwise_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_2_unit_2_sep2_data_conv2d_depthwise = convolution(vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_pad, group=10, strides=[1, 1], padding='VALID', name='vargface_stage_2_unit_2_sep2_data_conv2d_depthwise')
    vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_2_unit_2_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_bn')
    vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_bn, name='vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_act')
    vargface_stage_2_unit_2_sep2_data_conv2d_pointwise = convolution(vargface_stage_2_unit_2_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_2_unit_2_sep2_data_conv2d_pointwise')
    vargface_stage_2_unit_2_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_2_unit_2_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_2_sep2_data_conv2d_pointwise_bn')
    plus3           = vargface_stage_2_unit_2_sep2_data_conv2d_pointwise_bn + vargface_stage_2_unit_1_out_data_act
    vargface_stage_2_unit_2_out_data_act = prelu(plus3, name='vargface_stage_2_unit_2_out_data_act')
    vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_pad = tf.pad(vargface_stage_2_unit_2_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_2_unit_3_sep1_data_conv2d_depthwise = convolution(vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_pad, group=10, strides=[1, 1], padding='VALID', name='vargface_stage_2_unit_3_sep1_data_conv2d_depthwise')
    vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_2_unit_3_sep1_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_bn')
    vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_act = prelu(vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_bn, name='vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_act')
    vargface_stage_2_unit_3_sep1_data_conv2d_pointwise = convolution(vargface_stage_2_unit_3_sep1_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_2_unit_3_sep1_data_conv2d_pointwise')
    vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_2_unit_3_sep1_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_bn')
    vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_act = prelu(vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_bn, name='vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_act')
    vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_2_unit_3_sep1_data_conv2d_pointwise_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_2_unit_3_sep2_data_conv2d_depthwise = convolution(vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_pad, group=10, strides=[1, 1], padding='VALID', name='vargface_stage_2_unit_3_sep2_data_conv2d_depthwise')
    vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_2_unit_3_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_bn')
    vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_bn, name='vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_act')
    vargface_stage_2_unit_3_sep2_data_conv2d_pointwise = convolution(vargface_stage_2_unit_3_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_2_unit_3_sep2_data_conv2d_pointwise')
    vargface_stage_2_unit_3_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_2_unit_3_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_2_unit_3_sep2_data_conv2d_pointwise_bn')
    plus4           = vargface_stage_2_unit_3_sep2_data_conv2d_pointwise_bn + vargface_stage_2_unit_2_out_data_act
    vargface_stage_2_unit_3_out_data_act = prelu(plus4, name='vargface_stage_2_unit_3_out_data_act')
    vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_pad = tf.pad(vargface_stage_2_unit_3_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise = convolution(vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_pad, group=10, strides=[2, 2], padding='VALID', name='vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise')
    vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_pad = tf.pad(vargface_stage_2_unit_3_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise = convolution(vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_pad, group=10, strides=[2, 2], padding='VALID', name='vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise')
    vargface_stage_3_unit_1_shortcut_conv2d_depthwise_pad = tf.pad(vargface_stage_2_unit_3_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_1_shortcut_conv2d_depthwise = convolution(vargface_stage_3_unit_1_shortcut_conv2d_depthwise_pad, group=10, strides=[2, 2], padding='VALID', name='vargface_stage_3_unit_1_shortcut_conv2d_depthwise')
    vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_bn')
    vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_bn')
    vargface_stage_3_unit_1_shortcut_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_1_shortcut_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_1_shortcut_conv2d_depthwise_bn')
    vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_act = prelu(vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_bn, name='vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_act')
    vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_act = prelu(vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_bn, name='vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_act')
    vargface_stage_3_unit_1_shortcut_conv2d_depthwise_act = prelu(vargface_stage_3_unit_1_shortcut_conv2d_depthwise_bn, name='vargface_stage_3_unit_1_shortcut_conv2d_depthwise_act')
    vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise = convolution(vargface_stage_3_unit_1_sep1_data_branch_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise')
    vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise = convolution(vargface_stage_3_unit_1_sep2_data_branch_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise')
    vargface_stage_3_unit_1_shortcut_conv2d_pointwise = convolution(vargface_stage_3_unit_1_shortcut_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_1_shortcut_conv2d_pointwise')
    vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise_bn')
    vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise_bn')
    vargface_stage_3_unit_1_shortcut_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_1_shortcut_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_1_shortcut_conv2d_pointwise_bn')
    plus5           = vargface_stage_3_unit_1_sep1_data_branch_conv2d_pointwise_bn + vargface_stage_3_unit_1_sep2_data_branch_conv2d_pointwise_bn
    vargface_stage_3_unit_1_sep1_data_act = prelu(plus5, name='vargface_stage_3_unit_1_sep1_data_act')
    vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_1_sep1_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_1_sep2_data_conv2d_depthwise = convolution(vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_pad, group=20, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_1_sep2_data_conv2d_depthwise')
    vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_1_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_bn')
    vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_bn, name='vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_act')
    vargface_stage_3_unit_1_sep2_data_conv2d_pointwise = convolution(vargface_stage_3_unit_1_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_1_sep2_data_conv2d_pointwise')
    vargface_stage_3_unit_1_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_1_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_1_sep2_data_conv2d_pointwise_bn')
    plus6           = vargface_stage_3_unit_1_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_1_shortcut_conv2d_pointwise_bn
    vargface_stage_3_unit_1_out_data_act = prelu(plus6, name='vargface_stage_3_unit_1_out_data_act')
    vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_1_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_2_sep1_data_conv2d_depthwise = convolution(vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_pad, group=20, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_2_sep1_data_conv2d_depthwise')
    vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_2_sep1_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_bn')
    vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_act = prelu(vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_bn, name='vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_act')
    vargface_stage_3_unit_2_sep1_data_conv2d_pointwise = convolution(vargface_stage_3_unit_2_sep1_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_2_sep1_data_conv2d_pointwise')
    vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_2_sep1_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_bn')
    vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_act = prelu(vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_bn, name='vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_act')
    vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_2_sep1_data_conv2d_pointwise_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_2_sep2_data_conv2d_depthwise = convolution(vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_pad, group=20, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_2_sep2_data_conv2d_depthwise')
    vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_2_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_bn')
    vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_bn, name='vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_act')
    vargface_stage_3_unit_2_sep2_data_conv2d_pointwise = convolution(vargface_stage_3_unit_2_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_2_sep2_data_conv2d_pointwise')
    vargface_stage_3_unit_2_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_2_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_2_sep2_data_conv2d_pointwise_bn')
    plus7           = vargface_stage_3_unit_2_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_1_out_data_act
    vargface_stage_3_unit_2_out_data_act = prelu(plus7, name='vargface_stage_3_unit_2_out_data_act')
    vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_2_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_3_sep1_data_conv2d_depthwise = convolution(vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_pad, group=20, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_3_sep1_data_conv2d_depthwise')
    vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_3_sep1_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_bn')
    vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_act = prelu(vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_bn, name='vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_act')
    vargface_stage_3_unit_3_sep1_data_conv2d_pointwise = convolution(vargface_stage_3_unit_3_sep1_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_3_sep1_data_conv2d_pointwise')
    vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_3_sep1_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_bn')
    vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_act = prelu(vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_bn, name='vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_act')
    vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_3_sep1_data_conv2d_pointwise_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_3_sep2_data_conv2d_depthwise = convolution(vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_pad, group=20, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_3_sep2_data_conv2d_depthwise')
    vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_3_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_bn')
    vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_bn, name='vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_act')
    vargface_stage_3_unit_3_sep2_data_conv2d_pointwise = convolution(vargface_stage_3_unit_3_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_3_sep2_data_conv2d_pointwise')
    vargface_stage_3_unit_3_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_3_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_3_sep2_data_conv2d_pointwise_bn')
    plus8           = vargface_stage_3_unit_3_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_2_out_data_act
    vargface_stage_3_unit_3_out_data_act = prelu(plus8, name='vargface_stage_3_unit_3_out_data_act')
    vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_3_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_4_sep1_data_conv2d_depthwise = convolution(vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_pad, group=20, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_4_sep1_data_conv2d_depthwise')
    vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_4_sep1_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_bn')
    vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_act = prelu(vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_bn, name='vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_act')
    vargface_stage_3_unit_4_sep1_data_conv2d_pointwise = convolution(vargface_stage_3_unit_4_sep1_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_4_sep1_data_conv2d_pointwise')
    vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_4_sep1_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_bn')
    vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_act = prelu(vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_bn, name='vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_act')
    vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_4_sep1_data_conv2d_pointwise_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_4_sep2_data_conv2d_depthwise = convolution(vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_pad, group=20, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_4_sep2_data_conv2d_depthwise')
    vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_4_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_bn')
    vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_bn, name='vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_act')
    vargface_stage_3_unit_4_sep2_data_conv2d_pointwise = convolution(vargface_stage_3_unit_4_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_4_sep2_data_conv2d_pointwise')
    vargface_stage_3_unit_4_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_4_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_4_sep2_data_conv2d_pointwise_bn')
    plus9           = vargface_stage_3_unit_4_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_3_out_data_act
    vargface_stage_3_unit_4_out_data_act = prelu(plus9, name='vargface_stage_3_unit_4_out_data_act')
    vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_4_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_5_sep1_data_conv2d_depthwise = convolution(vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_pad, group=20, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_5_sep1_data_conv2d_depthwise')
    vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_5_sep1_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_bn')
    vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_act = prelu(vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_bn, name='vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_act')
    vargface_stage_3_unit_5_sep1_data_conv2d_pointwise = convolution(vargface_stage_3_unit_5_sep1_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_5_sep1_data_conv2d_pointwise')
    vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_5_sep1_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_bn')
    vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_act = prelu(vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_bn, name='vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_act')
    vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_5_sep1_data_conv2d_pointwise_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_5_sep2_data_conv2d_depthwise = convolution(vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_pad, group=20, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_5_sep2_data_conv2d_depthwise')
    vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_5_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_bn')
    vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_bn, name='vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_act')
    vargface_stage_3_unit_5_sep2_data_conv2d_pointwise = convolution(vargface_stage_3_unit_5_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_5_sep2_data_conv2d_pointwise')
    vargface_stage_3_unit_5_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_5_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_5_sep2_data_conv2d_pointwise_bn')
    plus10          = vargface_stage_3_unit_5_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_4_out_data_act
    vargface_stage_3_unit_5_out_data_act = prelu(plus10, name='vargface_stage_3_unit_5_out_data_act')
    vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_5_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_6_sep1_data_conv2d_depthwise = convolution(vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_pad, group=20, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_6_sep1_data_conv2d_depthwise')
    vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_6_sep1_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_bn')
    vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_act = prelu(vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_bn, name='vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_act')
    vargface_stage_3_unit_6_sep1_data_conv2d_pointwise = convolution(vargface_stage_3_unit_6_sep1_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_6_sep1_data_conv2d_pointwise')
    vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_6_sep1_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_bn')
    vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_act = prelu(vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_bn, name='vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_act')
    vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_6_sep1_data_conv2d_pointwise_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_6_sep2_data_conv2d_depthwise = convolution(vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_pad, group=20, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_6_sep2_data_conv2d_depthwise')
    vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_6_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_bn')
    vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_bn, name='vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_act')
    vargface_stage_3_unit_6_sep2_data_conv2d_pointwise = convolution(vargface_stage_3_unit_6_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_6_sep2_data_conv2d_pointwise')
    vargface_stage_3_unit_6_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_6_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_6_sep2_data_conv2d_pointwise_bn')
    plus11          = vargface_stage_3_unit_6_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_5_out_data_act
    vargface_stage_3_unit_6_out_data_act = prelu(plus11, name='vargface_stage_3_unit_6_out_data_act')
    vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_6_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_7_sep1_data_conv2d_depthwise = convolution(vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_pad, group=20, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_7_sep1_data_conv2d_depthwise')
    vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_7_sep1_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_bn')
    vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_act = prelu(vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_bn, name='vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_act')
    vargface_stage_3_unit_7_sep1_data_conv2d_pointwise = convolution(vargface_stage_3_unit_7_sep1_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_7_sep1_data_conv2d_pointwise')
    vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_7_sep1_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_bn')
    vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_act = prelu(vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_bn, name='vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_act')
    vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_7_sep1_data_conv2d_pointwise_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_3_unit_7_sep2_data_conv2d_depthwise = convolution(vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_pad, group=20, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_7_sep2_data_conv2d_depthwise')
    vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_3_unit_7_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_bn')
    vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_bn, name='vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_act')
    vargface_stage_3_unit_7_sep2_data_conv2d_pointwise = convolution(vargface_stage_3_unit_7_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_3_unit_7_sep2_data_conv2d_pointwise')
    vargface_stage_3_unit_7_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_3_unit_7_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_3_unit_7_sep2_data_conv2d_pointwise_bn')
    plus12          = vargface_stage_3_unit_7_sep2_data_conv2d_pointwise_bn + vargface_stage_3_unit_6_out_data_act
    vargface_stage_3_unit_7_out_data_act = prelu(plus12, name='vargface_stage_3_unit_7_out_data_act')
    vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_7_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise = convolution(vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_pad, group=20, strides=[2, 2], padding='VALID', name='vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise')
    vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_7_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise = convolution(vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_pad, group=20, strides=[2, 2], padding='VALID', name='vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise')
    vargface_stage_4_unit_1_shortcut_conv2d_depthwise_pad = tf.pad(vargface_stage_3_unit_7_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_4_unit_1_shortcut_conv2d_depthwise = convolution(vargface_stage_4_unit_1_shortcut_conv2d_depthwise_pad, group=20, strides=[2, 2], padding='VALID', name='vargface_stage_4_unit_1_shortcut_conv2d_depthwise')
    vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_bn = batch_normalization(vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_bn')
    vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_bn = batch_normalization(vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_bn')
    vargface_stage_4_unit_1_shortcut_conv2d_depthwise_bn = batch_normalization(vargface_stage_4_unit_1_shortcut_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_1_shortcut_conv2d_depthwise_bn')
    vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_act = prelu(vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_bn, name='vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_act')
    vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_act = prelu(vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_bn, name='vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_act')
    vargface_stage_4_unit_1_shortcut_conv2d_depthwise_act = prelu(vargface_stage_4_unit_1_shortcut_conv2d_depthwise_bn, name='vargface_stage_4_unit_1_shortcut_conv2d_depthwise_act')
    vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise = convolution(vargface_stage_4_unit_1_sep1_data_branch_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise')
    vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise = convolution(vargface_stage_4_unit_1_sep2_data_branch_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise')
    vargface_stage_4_unit_1_shortcut_conv2d_pointwise = convolution(vargface_stage_4_unit_1_shortcut_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_1_shortcut_conv2d_pointwise')
    vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise_bn = batch_normalization(vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise_bn')
    vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise_bn = batch_normalization(vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise_bn')
    vargface_stage_4_unit_1_shortcut_conv2d_pointwise_bn = batch_normalization(vargface_stage_4_unit_1_shortcut_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_1_shortcut_conv2d_pointwise_bn')
    plus13          = vargface_stage_4_unit_1_sep1_data_branch_conv2d_pointwise_bn + vargface_stage_4_unit_1_sep2_data_branch_conv2d_pointwise_bn
    vargface_stage_4_unit_1_sep1_data_act = prelu(plus13, name='vargface_stage_4_unit_1_sep1_data_act')
    vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_4_unit_1_sep1_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_4_unit_1_sep2_data_conv2d_depthwise = convolution(vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_pad, group=40, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_1_sep2_data_conv2d_depthwise')
    vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_4_unit_1_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_bn')
    vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_bn, name='vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_act')
    vargface_stage_4_unit_1_sep2_data_conv2d_pointwise = convolution(vargface_stage_4_unit_1_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_1_sep2_data_conv2d_pointwise')
    vargface_stage_4_unit_1_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_4_unit_1_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_1_sep2_data_conv2d_pointwise_bn')
    plus14          = vargface_stage_4_unit_1_sep2_data_conv2d_pointwise_bn + vargface_stage_4_unit_1_shortcut_conv2d_pointwise_bn
    vargface_stage_4_unit_1_out_data_act = prelu(plus14, name='vargface_stage_4_unit_1_out_data_act')
    vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_pad = tf.pad(vargface_stage_4_unit_1_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_4_unit_2_sep1_data_conv2d_depthwise = convolution(vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_pad, group=40, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_2_sep1_data_conv2d_depthwise')
    vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_4_unit_2_sep1_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_bn')
    vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_act = prelu(vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_bn, name='vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_act')
    vargface_stage_4_unit_2_sep1_data_conv2d_pointwise = convolution(vargface_stage_4_unit_2_sep1_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_2_sep1_data_conv2d_pointwise')
    vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_4_unit_2_sep1_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_bn')
    vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_act = prelu(vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_bn, name='vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_act')
    vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_4_unit_2_sep1_data_conv2d_pointwise_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_4_unit_2_sep2_data_conv2d_depthwise = convolution(vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_pad, group=40, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_2_sep2_data_conv2d_depthwise')
    vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_4_unit_2_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_bn')
    vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_bn, name='vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_act')
    vargface_stage_4_unit_2_sep2_data_conv2d_pointwise = convolution(vargface_stage_4_unit_2_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_2_sep2_data_conv2d_pointwise')
    vargface_stage_4_unit_2_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_4_unit_2_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_2_sep2_data_conv2d_pointwise_bn')
    plus15          = vargface_stage_4_unit_2_sep2_data_conv2d_pointwise_bn + vargface_stage_4_unit_1_out_data_act
    vargface_stage_4_unit_2_out_data_act = prelu(plus15, name='vargface_stage_4_unit_2_out_data_act')
    vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_pad = tf.pad(vargface_stage_4_unit_2_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_4_unit_3_sep1_data_conv2d_depthwise = convolution(vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_pad, group=40, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_3_sep1_data_conv2d_depthwise')
    vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_4_unit_3_sep1_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_bn')
    vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_act = prelu(vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_bn, name='vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_act')
    vargface_stage_4_unit_3_sep1_data_conv2d_pointwise = convolution(vargface_stage_4_unit_3_sep1_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_3_sep1_data_conv2d_pointwise')
    vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_4_unit_3_sep1_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_bn')
    vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_act = prelu(vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_bn, name='vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_act')
    vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_4_unit_3_sep1_data_conv2d_pointwise_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_4_unit_3_sep2_data_conv2d_depthwise = convolution(vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_pad, group=40, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_3_sep2_data_conv2d_depthwise')
    vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_4_unit_3_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_bn')
    vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_bn, name='vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_act')
    vargface_stage_4_unit_3_sep2_data_conv2d_pointwise = convolution(vargface_stage_4_unit_3_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_3_sep2_data_conv2d_pointwise')
    vargface_stage_4_unit_3_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_4_unit_3_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_3_sep2_data_conv2d_pointwise_bn')
    plus16          = vargface_stage_4_unit_3_sep2_data_conv2d_pointwise_bn + vargface_stage_4_unit_2_out_data_act
    vargface_stage_4_unit_3_out_data_act = prelu(plus16, name='vargface_stage_4_unit_3_out_data_act')
    vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_pad = tf.pad(vargface_stage_4_unit_3_out_data_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_4_unit_4_sep1_data_conv2d_depthwise = convolution(vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_pad, group=40, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_4_sep1_data_conv2d_depthwise')
    vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_4_unit_4_sep1_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_bn')
    vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_act = prelu(vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_bn, name='vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_act')
    vargface_stage_4_unit_4_sep1_data_conv2d_pointwise = convolution(vargface_stage_4_unit_4_sep1_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_4_sep1_data_conv2d_pointwise')
    vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_4_unit_4_sep1_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_bn')
    vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_act = prelu(vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_bn, name='vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_act')
    vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_pad = tf.pad(vargface_stage_4_unit_4_sep1_data_conv2d_pointwise_act, paddings = [[0, 0], [1, 1], [1, 1], [0, 0]])
    vargface_stage_4_unit_4_sep2_data_conv2d_depthwise = convolution(vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_pad, group=40, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_4_sep2_data_conv2d_depthwise')
    vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_bn = batch_normalization(vargface_stage_4_unit_4_sep2_data_conv2d_depthwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_bn')
    vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_act = prelu(vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_bn, name='vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_act')
    vargface_stage_4_unit_4_sep2_data_conv2d_pointwise = convolution(vargface_stage_4_unit_4_sep2_data_conv2d_depthwise_act, group=1, strides=[1, 1], padding='VALID', name='vargface_stage_4_unit_4_sep2_data_conv2d_pointwise')
    vargface_stage_4_unit_4_sep2_data_conv2d_pointwise_bn = batch_normalization(vargface_stage_4_unit_4_sep2_data_conv2d_pointwise, variance_epsilon=1.9999999494757503e-05, name='vargface_stage_4_unit_4_sep2_data_conv2d_pointwise_bn')
    plus17          = vargface_stage_4_unit_4_sep2_data_conv2d_pointwise_bn + vargface_stage_4_unit_3_out_data_act
    vargface_stage_4_unit_4_out_data_act = prelu(plus17, name='vargface_stage_4_unit_4_out_data_act')
    embed_convx     = convolution(vargface_stage_4_unit_4_out_data_act, group=1, strides=[1, 1], padding='VALID', name='embed_convx')
    embed_convx_bn  = batch_normalization(embed_convx, variance_epsilon=1.9999999494757503e-05, name='embed_convx_bn')
    embed_convx_act = prelu(embed_convx_bn, name='embed_convx_act')
    embed_convx_depthwise = convolution(embed_convx_act, group=128, strides=[1, 1], padding='VALID', name='embed_convx_depthwise')
    embed_convx_depthwise_bn = batch_normalization(embed_convx_depthwise, variance_epsilon=1.9999999494757503e-05, name='embed_convx_depthwise_bn')
    embed_convx_pointwise = convolution(embed_convx_depthwise_bn, group=1, strides=[1, 1], padding='VALID', name='embed_convx_pointwise')
    embed_convx_pointwise_bn = batch_normalization(embed_convx_pointwise, variance_epsilon=1.9999999494757503e-05, name='embed_convx_pointwise_bn')
    embed_convx_pointwise_act = prelu(embed_convx_pointwise_bn, name='embed_convx_pointwise_act')
    pre_fc1_flatten = tf.contrib.layers.flatten(embed_convx_pointwise_act)
    pre_fc1         = tf.layers.dense(pre_fc1_flatten, 512, kernel_initializer = tf.constant_initializer(__weights_dict['pre_fc1']['weights']), bias_initializer = tf.constant_initializer(__weights_dict['pre_fc1']['bias']), use_bias = True)
    fc1             = batch_normalization(pre_fc1, variance_epsilon=1.9999999494757503e-05, name='fc1')
    return data, fc1


def convolution(input, name, group, **kwargs):
    w = tf.Variable(__weights_dict[name]['weights'], trainable=is_train, name=name + "_weight")
    if group == 1:
        layer = tf.nn.convolution(input, w, name=name, **kwargs)
    else:
        weight_groups = tf.split(w, num_or_size_splits=group, axis=-1)
        xs = tf.split(input, num_or_size_splits=group, axis=-1)
        convolved = [tf.nn.convolution(x, weight, name=name, **kwargs) for
                    (x, weight) in zip(xs, weight_groups)]
        layer = tf.concat(convolved, axis=-1)

    if 'bias' in __weights_dict[name]:
        b = tf.Variable(__weights_dict[name]['bias'], trainable=is_train, name=name + "_bias")
        layer = layer + b
    return layer

def prelu(input, name):
    gamma = tf.Variable(__weights_dict[name]['gamma'], name=name + "_gamma", trainable=is_train)
    return tf.maximum(0.0, input) + gamma * tf.minimum(0.0, input)
    

def batch_normalization(input, name, **kwargs):
    mean = tf.Variable(__weights_dict[name]['mean'], name = name + "_mean", trainable = is_train)
    variance = tf.Variable(__weights_dict[name]['var'], name = name + "_var", trainable = is_train)
    offset = tf.Variable(__weights_dict[name]['bias'], name = name + "_bias", trainable = is_train) if 'bias' in __weights_dict[name] else None
    scale = tf.Variable(__weights_dict[name]['scale'], name = name + "_scale", trainable = is_train) if 'scale' in __weights_dict[name] else None
    return tf.nn.batch_normalization(input, mean, variance, offset, scale, name = name, **kwargs)


